### PR TITLE
Added filter and nested aggregations

### PR DESCRIPTION
**Pull request by nzcoffeem**
- Added filter and nested aggregations
- Added tests
- Updated readme

### CODE REVIEW

**Comment by mbuhot** [comment]
Thanks @nzcoffeem, looks great!

**Comment by nzcoffeem** [comment]
Thanks @mbuhot. Do you know when 0.7.0 will be published?

**Comment by mbuhot** [comment]
@nzcoffeem I'm having some issues with the bintray plugin.
I'll post the details in #34

**Comment by mbuhot** [comment]
@nzcoffeem Should be on bintray now :)

**Comment by nzcoffeem** [comment]
Thank you!

**Pull request merged**
